Create SideNav & Header
masaaki-todoroki/with-or-without-you pull request #3
Opened 2023-08-23 15:12 UTC by masaaki-todoroki

とりあえず、サイドナヴィゲーションとヘッダーのベースとなるものを作成してみました。
お手隙のときにご確認よろしくお願い致します。

2023-08-24 09:32 UTC, Naoto0213 requested changes
最初なので、細かい点を少し厳しめに見ました！
初心者とは思えない実装でびっくりしましたw
めちゃくちゃ綺麗に書けてます！

2023-08-24 09:32 UTC, Naoto0213 commented on pages/home.tsx
> +              <Button onClick={() => loginWithRedirect()}>ログイン</Button>
`isAuthenticated ? ... : `
の三項演算子を使用した方が一般的です！

2023-08-24 09:32 UTC, Naoto0213 commented on pages/index.tsx
> +const Index: CustomNextPage = () => {
`index`という命名は不透明なので、もう少し具代的にしたいですね。

2023-08-24 09:32 UTC, Naoto0213 commented on layout/DashboardLayout/DashboardLayout.tsx
> +import type { CustomLayout } from "next";
凄く細かいですが、

`layout/DashboardLayout` 
↓
`layout/dashboard`
で良いと思います。

1. ディレクトリ名は基本小文字スタート
2. layoutディレクトリなので、dashboardLayoutという命名は冗長

上記の理由です！

2023-08-24 09:32 UTC, Naoto0213 commented on component/PageContent/PageContent.tsx
> +      ) : null}
&&で良いかと！

```
  {outerTitle && (
        <Title order={2} mb="sm">
          {title}
        </Title>
      )}
```

2023-08-24 09:32 UTC, Naoto0213 commented on component/PageContent/PageContent.tsx
> +};
ComponentのPropsの命名は基本的にPropsで良いです！

```
type Props = {
  children: ReactNode;
  title: string;
  className?: string;
  outerTitle?: boolean;
};
```

2023-08-24 09:32 UTC, Naoto0213 commented on component/PageContainer/PageContainer.tsx
> +      ) : null}
三項演算子は不要かと思います！ 

```
 {items && items.length > 0 && (
        <Breadcrumbs>
          {items.map((item) => (
            <Link key={item.label} href={item.href} passHref>
              <Anchor>{item.label}</Anchor>
            </Link>
          ))}
        </Breadcrumbs>
      )}
```

2023-08-24 09:32 UTC, Naoto0213 commented on component/PageContainer/PageContainer.tsx
> +  items,
itemsなどの汎用的な命名は出来れば避けたいですね！

2023-08-24 09:32 UTC, Naoto0213 commented on layout/DashboardLayout/DashboardLayout.tsx
> +  return Header;
見た感じdynamic使用せずとも実装できるかなーと思ったのですが、dynamic採用した理由とかってありますか？

2023-08-24 09:32 UTC, Naoto0213 commented on layout/DashboardLayout/Header.tsx
> +export const Header: FC = () => {
```
export const Header: FC = () => {
```
という風にコンポーネント作成するのは正直あまり今は見かけませんね。
ひと昔前はあったんですけど。

今回はPropsがないので、下記で良いと思います！
```
export const Header = () => {
```

2023-08-24 09:32 UTC, Naoto0213 commented on layout/DashboardLayout/Header.tsx
> +};
return 省略出来ると思います！
https://chusotsu-program.com/react-return-omit/

2023-08-24 09:32 UTC, Naoto0213 commented on layout/DashboardLayout/SideNav.tsx
> +
長くなってしまうスタイリングに関しては別ファイルに分けた方が良いです！コンポーネント部分が見にくくなってしまうので！

layout/DashboardLayout/SideNav.styles.ts
とかですかね。

2023-08-24 09:32 UTC, Naoto0213 commented on lib/const/path.ts
> +};
getPathに関してはnextの
router.pathNameなどでも実装可能かなーと思ったのですが、いかがでしょうか！

2023-08-24 09:32 UTC, Naoto0213 commented on pages/home.tsx
> +Home.getLayout = DashboardLayout;
このレイアウトの指定方法とても良いですね☺️

2023-08-24 09:32 UTC, Naoto0213 commented on types/config/env.d.ts
> +}
素晴らしい🙌

2023-08-24 12:20 UTC, Naoto0213 commented on component/PageContent/PageContent.tsx
> +};
メモ: PropsにclassNameを使用するのは避ける

2023-08-24 12:22 UTC, Naoto0213 commented on component/PageContent/PageContent.tsx
> +      ) : null}
メモ: returnは省略出来る場合は省略する

2023-08-24 13:41 UTC, masaaki-todoroki commented on layout/DashboardLayout/DashboardLayout.tsx
> +  return Header;
すみません、ここちょっと分からなかったです。
もし違う書き方ありそうでしたら、ご教示頂けると嬉しいです！

2023-08-24 13:53 UTC, masaaki-todoroki commented on lib/const/path.ts
> +};
こちらいったんこのまま行かせて頂こうかと思います。

2023-08-24 14:40 UTC, masaaki-todoroki commented on pages/index.tsx
> +const Index: CustomNextPage = () => {
いったんAuthenticationにしておこうかと思います。
将来的に変わる可能性もあるかと思っております。

2023-08-26 09:07 UTC, masaaki-todoroki commented on component/PageContent/PageContent.tsx
> +};
classNameの代わりにsxを使うようにしてみました。

2023-08-27 10:16 UTC, Naoto0213 commented
LGTM!

2023-08-27 10:16 UTC, merged