[add] staff new create form
masaaki-todoroki/with-or-without-you pull request #4
Opened 2023-08-30 22:03 UTC by masaaki-todoroki

とりあえずReact Hook Formを使ってフォーム作成してみました。
zodのnumber型のバリデーションのカスタマイズがちょっとまだ理解できてないです。
（やりたかったのは、０以上の整数以外が入力されたら、自分で定義したエラーメッセージを出すということでしたが）
恐れ入りますが、ご確認よろしくお願い致します。

2023-08-31 05:25 UTC, Naoto0213 requested changes
軽くコメント残しました😌

2023-08-31 05:25 UTC, Naoto0213 commented on pages/staff/new-create.tsx
> +    message: "半角英数記号で入力してください。"
Zod等のフォームバリデーションに関しては、別ファイルに切り出した方がコンポーネントとしての可読性上がると思います☺️

2023-08-31 05:25 UTC, Naoto0213 commented on pages/staff/new-create.tsx
> +const STAFF_NEW_CREATE: CustomNextPage = () => {
キャメルケースが正しいかと！

2023-08-31 05:25 UTC, Naoto0213 commented on pages/staff/new-create.tsx
> +    ),
細かくバリデーション出来てて素晴らしいですね！

2023-08-31 05:25 UTC, Naoto0213 commented on pages/staff/new-create.tsx
> +  };
letとif文を使用した配列生成等はあまり実戦では行いません。
ここに関してはMTGで解説しますね。

2023-08-31 05:25 UTC, Naoto0213 commented on pages/staff/new-create.tsx
> +  const onSubmit = (data: RegisterStaffInputType) => console.log(data);
dataではなく、valueが適切な命名かと！

2023-08-31 05:25 UTC, Naoto0213 commented on pages/staff/new-create.tsx
> +type RegisterStaffInputType = z.infer<typeof RegisterStaffSchema>;
RegisterStaffInputTypeではなく、

FormValuesやCreateStaffFormValue等が適切だと思います！

2023-08-31 05:25 UTC, Naoto0213 commented on pages/staff/new-create.tsx
> +    let { value } = event.target;
valueのみ必要な場合は、中身のvalueだけ型指定してすると短くなりますよ！
```
  onChange={(e) => handleMobileInputChange(e.target.value)}
```
```
 const handleMobileInputChange = (
    value: string
  ) => {
```

2023-08-31 05:25 UTC, Naoto0213 commented on pages/staff/new-create.tsx
> +                  }
ぱっとみ何の関数か理解出来ないので、別関数にして命名で理解させるか、コメントアウト等残しておくと良いですね

2023-08-31 05:25 UTC, Naoto0213 commented on pages/staff/new-create.tsx
> +              </Text>
細かいですが、MantineにはInput.wrapperという物があるのでそちらを利用してエラーなどを表示したいですね。
https://mantine.dev/core/input/

```
import { Input } from '@mantine/core';

function Demo() {
  return (
    <Input.Wrapper
      id="input-demo"
      withAsterisk
      label="Credit card information"
      description="Please enter your credit card information, we need some money"
      error="Your credit card expired"
    >
      <Input id="input-demo" placeholder="Your email" />
    </Input.Wrapper>
  );
}
```

2023-08-31 12:18 UTC, Naoto0213 commented on pages/staff/new-create.tsx
> +  };
letとfor文

2023-08-31 12:21 UTC, Naoto0213 commented on pages/staff/new-create.tsx
> +                placeholder=""
空文字は必要ありません

2023-09-02 08:40 UTC, masaaki-todoroki commented
リファクタリングしてみました。
ご確認よろしくお願いします。

2023-09-02 08:42 UTC, masaaki-todoroki commented on pages/staff/new-create.tsx
> +              </Text>
<TextInput
  error={errors.email?.message}
/>
みたいな感じでできそうだったので、それでやってみました。
（この間のMTGで町田さんが実演してくださった形です。）

2023-09-02 08:42 UTC, masaaki-todoroki commented on pages/staff/new-create.tsx
> +type RegisterStaffInputType = z.infer<typeof RegisterStaffSchema>;
CreatedStaffValue としてみました。

2023-09-02 08:43 UTC, masaaki-todoroki commented on pages/staff/new-create.tsx
> +  const onSubmit = (data: RegisterStaffInputType) => console.log(data);
createdStaffValue としてみました。

2023-09-02 08:43 UTC, masaaki-todoroki commented on pages/staff/new-create.tsx
> +  };
ここは不要との方向性で削除しました。

2023-09-02 08:44 UTC, masaaki-todoroki commented on pages/staff/new-create.tsx
> +    ),
シンプルにしてみましたw

2023-09-06 13:55 UTC, masaaki-todoroki commented
スタッフのデータをDBに格納するところまで、いったんできたかなと思います。
ご確認よろしくお願い致します！

2023-09-06 17:38 UTC, Naoto0213 requested changes
軽くレビューしました！

2023-09-06 17:38 UTC, Naoto0213 commented on queries/queries.ts
> +`;
ばっちりです！

2023-09-06 17:38 UTC, Naoto0213 commented on pages/staff/new-create.tsx
> +  });
submittedDataでは、何のsubmmitされたデータなのか理解出来ないので不適切だと思います。
例えば今回では
`createdStaff`とかだとわかりやすいですかね。

2023-09-06 17:38 UTC, Naoto0213 commented on pages/staff/new-create.tsx
> +  }, [id, setValue]);
idだけだと、何のidか。という情報が抜けていると思います！ 目的語 + 単語を心がけると良いです。
今回だったら`userId`ですね。

2023-09-06 17:38 UTC, Naoto0213 commented on pages/staff/new-create.tsx
> +  const id = userData?.users[0].id;
GET_USERSではなく、GET_USERで単一のuserIdを取って来れませんか？

2023-09-06 17:38 UTC, Naoto0213 commented on pages/staff/new-create.tsx
> +  });
それと、恐らくreact-hook-formのformStateを使用すればuseStateを使用せずに実装出来ると思いました！

2023-09-06 17:38 UTC, Naoto0213 commented on pages/staff/new-create.tsx
> +            )}
この様なデザインはToastが使用されるのが一般的だと思います！

2023-09-06 21:42 UTC, masaaki-todoroki commented on pages/staff/new-create.tsx
> +  });
なるほどです！

2023-09-06 21:43 UTC, masaaki-todoroki commented on pages/staff/new-create.tsx
> +  }, [id, setValue]);
了解です！

2023-09-06 21:44 UTC, masaaki-todoroki commented on pages/staff/new-create.tsx
> +  const id = userData?.users[0].id;
再考してみます！

2023-09-06 21:44 UTC, masaaki-todoroki commented on pages/staff/new-create.tsx
> +            )}
なるほどです！
再考してみます！

2023-09-07 05:45 UTC, Naoto0213 commented on queries/queries.ts
> +`;
@masaaki-todoroki 
あ、GraphQLからフロントに持って来る時は一旦キャメルケースに直すのが一般的です。

```
export const GET_STAFF = gql`
  query GetStaff {
    staff {
      email
      name
      nickname
      age
      mobile
      line_id: lineId
      x_username: xUserName
    }
  }
`;
```

2023-09-07 11:39 UTC, masaaki-todoroki commented on queries/queries.ts
> +`;
なるほどです！

2023-09-08 06:48 UTC, Naoto0213 requested changes

2023-09-08 06:48 UTC, Naoto0213 commented on types/generated/gql.ts
gitignore

2023-09-08 06:48 UTC, Naoto0213 commented on pages/staff/new-create.tsx
> +  };
useCallbackとかで重そうな処理はくくっておく

2023-09-08 06:48 UTC, Naoto0213 commented on pages/staff/new-create.tsx
> +  const id = userData?.users[0].id;
users_by_pk

2023-09-08 06:48 UTC, Naoto0213 commented on pages/staff/new-create.tsx
> +      });
const result = ...
setSubmittedData(result);

2023-09-10 02:35 UTC, masaaki-todoroki commented on pages/staff/new-create.tsx
> +  }, [id, setValue]);
この部分、recoilを使って書き直しました。
↓この
const { isAuthenticated, loginWithRedirect, logout, user } = useAuth0();
userで取得できるuser.subというのに、
user_idに相応しいと思われる値が入っていたので、
その値をrecoilで管理して、別のページでも使うみたいな感じでやってみました。

2023-09-10 02:35 UTC, masaaki-todoroki commented on pages/staff/new-create.tsx
> +            )}
右下に出るようにしてみました。

2023-09-10 02:36 UTC, masaaki-todoroki commented on types/generated/gql.ts
types/generated配下全てのファイルとgraphql.schema.jsonファイルをgitignoreしときました。

2023-09-10 02:49 UTC, masaaki-todoroki commented on pages/staff/new-create.tsx
> +  };
了解です。

2023-09-10 04:08 UTC, masaaki-todoroki commented
users_by_pk でuserテーブルのidを取得しようと先日仰られていたかと思います。
その点以下のようにしてみました。
↓
pages/index.tsx（いったん仮でこのファイル）で以下のようにしてあったのですが、
const { isAuthenticated, loginWithRedirect, logout, user } = useAuth0(); 
このuserで取得できるuser.subというプロパティに、
僕がstaffテーブルのuser_idにしようと思っていたものが入っていたので、
その値をrecoilで管理して、別のページでも使うみたいな感じでやってみました。

2023-09-10 13:42 UTC, Naoto0213 requested changes
一点だけ！！
Recoilを使用するという発想はとても良いと思います☺️

2023-09-10 13:42 UTC, Naoto0213 commented on pages/staff/new-create.tsx
>                />
こちらのTextInput不要かと思います！
userIdを直接Userが入力することは無いと思うので！

2023-09-10 13:42 UTC, Naoto0213 commented on pages/staff/new-create.tsx
> +  }, [loginUser]);
user情報の取得は、useAuth0から取得出来ると思います☺️
なので、recoil等での状態管理は不要ですね。

2023-09-10 13:42 UTC, Naoto0213 commented on pages/index.tsx
> +  }, [user]);
他のコンポーネントでも同様に、
```
  const { isAuthenticated, loginWithRedirect, logout, user } = useAuth0();
```
useAuth0からユーザー情報取得するのが良いですね！recoilは不要です。

2023-09-10 13:42 UTC, Naoto0213 commented on .gitignore
> +graphql.schema.json
ありがとうございます🙌

2023-09-10 13:44 UTC, Naoto0213 commented on pages/index.tsx
> +  }, [user]);
ちなみに、setだけしたい場合は、`useSetRecoilState` がおすすめです。

2023-09-10 21:41 UTC, masaaki-todoroki commented on pages/staff/new-create.tsx
>                />
そうですね、直接Userは入力することはないので、コードの処理で裏で入力させている感じになります。

というのは、staffテーブルにuser_idカラムを設けてあります。↓
![スクリーンショット 2023-09-11 6 33 44](https://github.com/masaaki-todoroki/with-or-without-you/assets/46153747/17aac942-8c4d-4ac0-9b8f-7246ac627686)

それは、selectとかのPermissionの設定の際、staffにこのuser_idが紐づいていないと、制御できないから、という考えからになります。↓
![スクリーンショット 2023-09-11 6 34 41](https://github.com/masaaki-todoroki/with-or-without-you/assets/46153747/6292e7fc-0942-40c4-8a10-3ccc1869c58e)

（単なるidは自動採番でincrementされていくものになります。）

なので自分としては必要かなと思っているのですが、自分の認識がずれていたらご指摘頂けると嬉しいです！
よろしくお願いします。

2023-09-10 21:49 UTC, masaaki-todoroki commented on pages/staff/new-create.tsx
> +  }, [loginUser]);
こちら理解しました！

2023-09-10 21:49 UTC, masaaki-todoroki commented on pages/index.tsx
> +  }, [user]);
こちら理解しました！

2023-09-11 06:09 UTC, Naoto0213 commented on pages/staff/new-create.tsx
>                />
> そうですね、直接Userは入力することはないので、コードの処理で裏で入力させている感じになります。

そうです！裏で入力させる処理は必要だと思います。
useEffectでuser情報をsetしている箇所ですね。こちらは必要です👍

ですが、こちらのコードは必要ですか？
恐らくこちらのコード削除しても同様に動作すると思います！
動かない場合また教えてください！
```
 <TextInput
                type="hidden"
                {...register("userId", { required: true })}
              />
 ```

2023-09-11 15:34 UTC, Naoto0213 commented on pages/staff/new-create.tsx
> +  }, [loginUser]);
@masaaki-todoroki 
それと、// eslint-disable-next-lineする際は理由を一言載せていただけますとレビューしやすいです！
今回の理由だと何になりますか？

2023-09-12 13:34 UTC, masaaki-todoroki commented on pages/staff/new-create.tsx
>                />
userFormから抽出しているsetValueで、react-hook-form的にはセットできているので、
inputタグにセットする必要はないってことですね！？
理解できました。
有難うございます！

2023-09-12 13:42 UTC, masaaki-todoroki commented on pages/staff/new-create.tsx
> +  }, [loginUser]);
@Naoto0213 
setValueを追加して、「// eslint-disable-next-line」は削除しました！

たしかこのコミットしたときは、loginUserだけだとエラー（波線）が出ていたと思います。
で、setValueも追加する必要がある的なサジェストが出ていたような気がするのですが、
自分の思考的に、setValueってメソッド的なものであって、変数ではないよね？と思って、
依存配列に入れる必要はないと判断してしまって、// eslint-disable-next-line を入れたのかなと思います。

このへん、もし自分の認識がアレでしたら、アドバイス頂けると嬉しいです！

2023-09-12 14:32 UTC, Naoto0213 commented on pages/staff/new-create.tsx
> +  }, [loginUser]);
setValueは依存配列に入れてしまって良いと思います！
変数だけではなく、関数も依存配列に入ることは結構あります〜

2023-09-12 14:33 UTC, Naoto0213 approved these changes
LGTM!

2023-09-12 14:33 UTC, merged