[add] base of view for staff data
masaaki-todoroki/with-or-without-you pull request #5
Opened 2023-09-13 21:27 UTC by masaaki-todoroki

■フォーム
以下の入力項目を追加しました。
「ローマ字ニックネーム」「身長」「血液型」「紹介文」

■一覧ページ
とりあえずファイル内でスタッフデータ10人分をconstで定義して、mapでぐるぐる回して表示させています。

■詳細ページ
urlが /staff?=ローマ字ニックネーム みたいになるような感じでやりたかったのですが、
時間がなくそこまでできなかったので、
いったんdetail.tsxというファイルを作ってそこで簡単なレイアウトだけ作ってみました。

レビューよろしくお願い致します！🙇‍♂️

2023-09-14 04:22 UTC, Naoto0213 requested changes
レビューしました！

2023-09-14 04:22 UTC, Naoto0213 commented on components/VerticalSplitContentCard.tsx
> +  <Grid.Col xs={xs}>
Gridを使用する際は複雑なレイアウトを組む時に限った方がよいです！
今回の様に縦並びにしたいだけであれば、Flexを使用した方が適切かと思います。

2023-09-14 04:22 UTC, Naoto0213 commented on components/VerticalSplitContentCard.tsx
> +  xs: number;
sx, xsという命名では、ぱっと見で何のPropsか理解出来ないのでもう少し具体的な名前を付けると良いです。

2023-09-14 04:22 UTC, Naoto0213 commented on components/VerticalSplitContentCard.tsx
> +export const VerticalSplitContentCard: FC<Props> = ({
コンポーネント名は可能だけ短く、でも的確な命名が求められるます(難しいですよね)

今回だともう少しシンプルに、ContainerCardなどの汎用性がある命名でも良いと思います。

2023-09-14 04:22 UTC, Naoto0213 commented on pages/staff/detail.tsx
> +  const [staffMainImageSrc, setStaffMainImageSrc] = useState(
staffImageSrcでも意味は通じると思います！

2023-09-14 04:22 UTC, Naoto0213 commented on pages/staff/detail.tsx
> +  };
正直1行程度の関数ならonClickにそのまま書いてしまうケースが多いですね！

```
onClick={() => setStaffMainImageSrc(url)}
```

2023-09-14 04:22 UTC, Naoto0213 commented on pages/staff/index.tsx
> +                    ref={cardRef}
このrefって必要ですか？

2023-09-14 11:35 UTC, masaaki-todoroki commented on pages/staff/index.tsx
> +                    ref={cardRef}
必要ないっすねw
エフェクトつけうようと思ってちょっといじった時の残骸ですww

2023-09-14 11:35 UTC, masaaki-todoroki commented on pages/staff/detail.tsx
> +  };
なるほどっす！

2023-09-14 11:36 UTC, masaaki-todoroki commented on pages/staff/detail.tsx
> +  const [staffMainImageSrc, setStaffMainImageSrc] = useState(
ですね！

2023-09-14 11:40 UTC, masaaki-todoroki commented on components/VerticalSplitContentCard.tsx
> +  xs: number;
ですね！

2023-09-21 12:48 UTC, Naoto0213 requested changes

2023-09-21 12:48 UTC, Naoto0213 commented on components/FileValueComponent.tsx
> +export const Value: React.FC<{ file: File }> = ({ file }) => {
React.FCは使用しなくても良い

2023-09-21 12:48 UTC, Naoto0213 commented on features/staff/helper/validation.ts
> +  // staffId: z.number(),
不要ですね

2023-09-21 12:48 UTC, Naoto0213 commented on pages/staff/index.tsx
> +                      <Text weight={900} size={"xl"}>
weight="bold"

2023-09-21 12:48 UTC, Naoto0213 commented on pages/staff/index.tsx
> +                        style={{ marginTop: "0" }}
const router = useRouter()

<Button onClick={() => router.push(getPath("STAFF_DETAIL")) />

2023-09-21 12:48 UTC, Naoto0213 commented on pages/staff/new-create.tsx
> +type TotalStaffData = z.infer<typeof StaffTotalValidation>;
type StaffFormValue

2023-09-21 12:48 UTC, Naoto0213 commented on pages/staff/new-create.tsx
>    }, [user, setValue]);
そのままつっこむ

2023-09-21 12:48 UTC, Naoto0213 commented on pages/staff/new-create.tsx
> +  };
utilsに移籍

2023-09-21 12:48 UTC, Naoto0213 commented on pages/staff/new-create.tsx
> +  const { uploadToS3 } = useUploadToS3();
カスタムフックは可能なだけ上の方で書く

2023-09-21 12:48 UTC, Naoto0213 commented on queries/queries.ts
>  `;
queriesに書くのではなく、GraphQL文はfeatures/staffに書くgraphql.tsxにする

2023-09-21 12:48 UTC, Naoto0213 commented on utils/useUploadToS3.ts
> +  return { uploadToS3 };
loadingを追加

2023-09-21 12:48 UTC, Naoto0213 commented on pages/staff/new-create.tsx
> +              />
Controllerを使用できたらなお良い

2023-09-21 12:48 UTC, Naoto0213 commented on pages/staff/new-create.tsx
> +  const [registerStaffThumbnails] =
loadingの処理を書く

2023-09-21 12:48 UTC, Naoto0213 commented on pages/staff/index.tsx
> +          </Button>
onClickで

2023-09-21 12:48 UTC, Naoto0213 commented on utils/useUploadToS3.ts
> +        return null;
toastでエラー表示

2023-09-28 22:29 UTC, masaaki-todoroki commented
レビューよろしくお願いいたします！🙇

2023-09-29 03:47 UTC, Naoto0213 requested changes
コメント残しましたー！ここ修正できたらマージしましょうか！

2023-09-29 03:47 UTC, Naoto0213 commented on components/ContentCard.tsx
> +  pos?: "relative";
sxの中でposition:relativeの指定って出来ないんですかね？
それと、型定義でrelative固定になっているので、あまり意味ないかなと思ってしました！

2023-09-29 03:47 UTC, Naoto0213 commented on components/FileBadgeList.tsx
> +export const FileBadge = ({ file }: Props) => {
分かりやすくて良い命名だと思います☺️

2023-09-29 03:47 UTC, Naoto0213 commented on pages/staff/[nickname].tsx
> +  /* パスパラメータからnicknameを取得 */
余分なコメントは消しておいた方が可読性上がります！

2023-09-29 03:47 UTC, Naoto0213 commented on pages/staff/[nickname].tsx
> +      skip: !nickname,
skip使えてるの良いですね☺️

2023-09-29 03:47 UTC, Naoto0213 commented on pages/staff/[nickname].tsx
> +      skip: !nickname,
んーでも、ニックネームからスタッフのデータを取得するのは変かなと。
StaffIdからが適切じゃないですかね？

2023-09-29 03:47 UTC, Naoto0213 commented on pages/staff/[nickname].tsx
> +  const [selectedImage, setSelectedImage] = useState<string | null>(null);
現在はnullは使用せずにundefinedを使用するケースが殆どですね

2023-09-29 03:47 UTC, Naoto0213 commented on pages/staff/[nickname].tsx
> +          <Box sx={{ marginBottom: "16px" }}>
marginの指定って
```
<Box mb="16px" /> 
```
とかで出来ませんかね？

2023-09-29 03:47 UTC, Naoto0213 commented on pages/staff/[nickname].tsx
> +  const { nickname } = router.query;
恐らくここでは、idを受け取るのが正しいですね！

2023-09-29 03:47 UTC, Naoto0213 commented on pages/staff/index.tsx
> +  const { data, loading, error } = useQuery<GetStaffQuery>(GET_STAFF);
dataという命名だと分かりにくいので、
staffDataという様に明確化しておくと分かりやすいですね☺️

2023-09-29 03:47 UTC, Naoto0213 commented on pages/staff/new-create.tsx
> +  const { uploadToS3, s3Loading } = useUploadToS3();
めっちゃ良い感じです！！

2023-09-29 03:47 UTC, Naoto0213 commented on pages/staff/new-create.tsx
> +        setFileInputKey((prevKey) => prevKey + 1);
ここ必要ですかね？後で見ますね！

2023-09-29 03:47 UTC, Naoto0213 commented on pages/staff/new-create.tsx
>                />
良いですね☺️

2023-09-29 03:47 UTC, Naoto0213 commented on utils/useUploadToS3.tsx
> +const resizeImageTo3by4 = async (file: File): Promise<Blob> => {
resizeImageだけの方が分かりやすいかなと思いました。

2023-09-29 03:47 UTC, Naoto0213 commented on utils/useUploadToS3.tsx
> +const resizeImageTo3by4 = async (file: File): Promise<Blob> => {
Promise<Blob>こちらのreturnの型定義って必要ですかね？

2023-09-29 03:47 UTC, Naoto0213 commented on utils/useUploadToS3.tsx
> +  const [s3Loading, setS3Loading] = useState<boolean>(false);
const [s3Loading, setS3Loading] = useState<boolean>(false);
  
  こちらも
  const [loading, setLoading] = useState(false);
  
  で良いかと思います。
  useStateの型定義は不要なのかなと！

2023-09-29 03:47 UTC, Naoto0213 commented on utils/useUploadToS3.tsx
> +      const resizedBlob = await resizeImageTo3by4(file);
良いですねー！！

2023-09-29 13:14 UTC, Naoto0213 requested changes
軽くコメント残しました！

2023-09-29 13:14 UTC, Naoto0213 commented on components/StaffValueText.tsx
> +      style={{
sxで良いと思います。

2023-09-29 13:14 UTC, Naoto0213 commented on components/StaffValueText.tsx
> +      style={{
<Box>コンポーネントでくくる

2023-09-29 13:14 UTC, Naoto0213 commented on components/StaffValueText.tsx
> +const StaffValueText = ({ children, ...props }: Props) => {
![スクリーンショット 2023-09-29 21 26 03](https://github.com/masaaki-todoroki/with-or-without-you/assets/82670491/acfd66c0-38fc-4816-bbe3-01abae0e2c0d)

ここまでをコンポーネントとして持たせる

2023-09-29 13:14 UTC, Naoto0213 commented on components/StaffValueText.tsx
features/staff/component/...

2023-09-29 13:14 UTC, Naoto0213 commented on components/FileBadgeList.tsx
> +        padding: `${rem(3)} ${rem(7)}`,
remは使用せずにpxで

2023-09-29 13:14 UTC, Naoto0213 commented on components/StaffValueText.tsx
> +      }}
コンポーネントにベタ書きで良い

2023-09-29 13:14 UTC, Naoto0213 commented on features/staff/helper/graphql.ts
> +export const GET_STAFF = gql`
GET_STAFF_LIST

2023-09-29 13:14 UTC, Naoto0213 commented on pages/staff/[nickname].tsx
> +  const [selectedImage, setSelectedImage] = useState<string | null>(null);
selectedImageUrl or selectedImageSrc が良い

2023-09-29 13:14 UTC, Naoto0213 commented on pages/staff/[nickname].tsx
> +  const [selectedImage, setSelectedImage] = useState<string | null>(null);
useState<string>();

2023-09-29 13:14 UTC, Naoto0213 commented on pages/staff/[nickname].tsx
> +  const [selectedImage, setSelectedImage] = useState<string | null>(null);
const [selectedThumbnaileUrl, setSelectedImage] = useState<string>(thumbnaile);

2023-09-29 13:14 UTC, Naoto0213 commented on pages/staff/[nickname].tsx
> +  const [selectedImage, setSelectedImage] = useState<string | null>(null);
thumbnailes.first()

2023-09-29 13:14 UTC, Naoto0213 commented on pages/staff/[nickname].tsx
> +          <Box>
いらないかも

2023-09-29 13:14 UTC, Naoto0213 commented on pages/staff/[nickname].tsx
> +            <Title order={6}>ニックネーム</Title>
{staff &&

2023-09-29 13:14 UTC, Naoto0213 commented on pages/staff/[nickname].tsx
> +            <Title order={6}>ニックネーム</Title>
<HogeConteiner my="12px" />
<HogeConteiner my="12px" />
<HogeConteiner my="12px" />

2023-09-29 13:14 UTC, Naoto0213 commented on pages/staff/[nickname].tsx
> +            <Title order={6}>ニックネーム</Title>
<HogeConteiner my="12px" />

2023-09-29 13:14 UTC, Naoto0213 commented on pages/staff/[nickname].tsx
> +            <Title order={6}>ニックネーム</Title>
```
<HogeConteiner my="12px" />
```

2023-09-29 13:14 UTC, Naoto0213 commented on pages/staff/index.tsx
> +  const { data, loading, error } = useQuery<GetStaffQuery>(GET_STAFF);
const staff = staffData.staff

2023-09-29 13:14 UTC, Naoto0213 commented on pages/staff/index.tsx
if(!data) return <Loading/>

2023-09-29 13:14 UTC, Naoto0213 commented on pages/staff/new-create.tsx
> +  const [fileInputKey, setFileInputKey] = useState<number>(0);
遷移すればよくね

2023-09-29 13:14 UTC, Naoto0213 commented on pages/staff/new-create.tsx
> +          <form onSubmit={handleSubmit(onSubmit, (e) => console.log(e))}>
(e) => console.log(e)
消しておいてください🙏

2023-09-29 13:14 UTC, Naoto0213 commented on utils/useUploadToS3.tsx
hooksディレクトリに入れる

2023-09-30 04:31 UTC, masaaki-todoroki commented on components/ContentCard.tsx
> +  pos?: "relative";
sxでできました。

2023-09-30 04:31 UTC, masaaki-todoroki commented on pages/staff/[nickname].tsx
> +  /* パスパラメータからnicknameを取得 */
了解です！

2023-09-30 04:33 UTC, masaaki-todoroki commented on pages/staff/[nickname].tsx
> +  const [selectedImage, setSelectedImage] = useState<string | null>(null);
firstというのは使えませんでした。
以下のようにしました。
また、useEffectを使わないと、最初ロードしたとき表示されなかったので、使ってあります。
  const thumbnail =
    staff && staff.staff_thumbnails && staff.staff_thumbnails[0]
      ? staff.staff_thumbnails[0].thumbnail_url
      : undefined;
  const [selectedImageUrl, setSelectedImageUrl] = useState(thumbnail);
  useEffect(() => {
    setSelectedImageUrl(thumbnail);
  }, [thumbnail]);

2023-09-30 04:37 UTC, masaaki-todoroki commented on pages/staff/[nickname].tsx
> +          <Box sx={{ marginBottom: "16px" }}>
mb="16px" または mb={16} でいけました。
が、ここmarginいらないかなと思ったのでww、削除しときます。

2023-09-30 04:57 UTC, masaaki-todoroki commented on utils/useUploadToS3.tsx
> +const resizeImageTo3by4 = async (file: File): Promise<Blob> => {
ここはアリな感じでお願いします！

2023-10-01 02:57 UTC, Naoto0213 commented on pages/staff/[nickname].tsx
> +  const [selectedImage, setSelectedImage] = useState<string | null>(null);
あれ、なんでだろう😅
了解しました！

2023-10-01 08:39 UTC, masaaki-todoroki commented on pages/staff/new-create.tsx
> +        setFileInputKey((prevKey) => prevKey + 1);
登録後、画面遷移するようにしたので、削除しました。

2023-10-01 09:02 UTC, masaaki-todoroki commented
リファクタリングしてみました。
ご確認お願い致します！🙇‍♂️

2023-10-01 16:51 UTC, Naoto0213 requested changes
レビューしました！

2023-10-01 16:51 UTC, Naoto0213 commented on components/FileBadgeList.tsx
> +        padding: "3px 7px",
px指定は可能なだけ4の倍数に合わせた方が良いです！

2023-10-01 16:51 UTC, Naoto0213 commented on features/staff/component/StaffDataContainer.tsx
> +const StaffDataContainer = ({ title, staffData }: Props) => {
Dataという命名は基本的にNGです！
StaffDetailTextContainerとかですかね

2023-10-01 16:51 UTC, Naoto0213 commented on features/staff/component/StaffDataContainer.tsx
> +  staffData?: string | number | undefined | null;
こちらもDataという命名はNGですね！それとnullの型定義も避けてください。
オプショナルにしているので、undefinedの指定も不要ですね。

2023-10-01 16:51 UTC, Naoto0213 commented on pages/staff/[id].tsx
> +              </Box>
ここのBoxは不要かと！

2023-10-01 16:51 UTC, Naoto0213 commented on features/staff/component/StaffDataContainer.tsx
> +    <>
フラグメントは避けてBoxを使用してください！

2023-10-01 16:51 UTC, Naoto0213 commented on pages/staff/[id].tsx
> +  }
やるならuseEffectが適切ですね。

2023-10-01 16:51 UTC, Naoto0213 commented on pages/staff/[id].tsx
> +  if (!staffData) return null;
nullの指定はNGです！
スタッフデータが見つかりませんでした。的な<Text>で返すと良いと思います。

2023-10-01 16:51 UTC, Naoto0213 commented on pages/staff/[id].tsx
> +                        cursor: "pointer"
コンポーネントにベタ書きで良いと思います！無理だったらすみません。
cursor="pointer"

2023-10-01 16:51 UTC, Naoto0213 commented on pages/staff/index.tsx
> +    "https://images.unsplash.com/photo-1515138692129-197a2c608cfd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=300&h=400&q=80";
ここの画像データはurlではなく、pngなどでpublicに置いておくのが適切ですね。

2023-10-01 16:51 UTC, Naoto0213 commented on pages/staff/index.tsx
> +  if (!staffListData) return null;
こちらもnull指定はNGです！

2023-10-01 16:51 UTC, Naoto0213 commented on pages/staff/index.tsx
>                            }
コンポーネントにベタ書きでいけるかと！

2023-10-01 16:51 UTC, Naoto0213 commented on pages/staff/new-create.tsx
> +        router.push(getPath("STAFF_DETAIL", staffFormValue.nicknameInEnglish));
ここ、idを渡すのが適切かと！

2023-10-02 11:59 UTC, masaaki-todoroki commented on pages/staff/[id].tsx
> +                        cursor: "pointer"
こちら無理そうでした🙇‍♂️

2023-10-02 13:46 UTC, masaaki-todoroki commented on pages/staff/[id].tsx
> +  }
エラー用のコンポーネントを一つ作ってやってみました。
（なのでuseEffectは使わない方向です。）

2023-10-02 13:47 UTC, masaaki-todoroki commented on pages/staff/[id].tsx
> +  if (!staffData) return null;
エラー用のコンポーネントを一つ作ってやってみました。（上のと同じですが）
messageをpropsで渡すようにしてやってみました。

2023-10-02 13:48 UTC, masaaki-todoroki commented on pages/staff/index.tsx
> +  if (!staffListData) return null;
エラー用のコンポーネントを一つ作ってやってみました。
messageをpropsで渡すようにしてやってみました。

2023-10-02 14:22 UTC, masaaki-todoroki commented
度々すみません、リファクタリングしてみました。
お手隙の時にご確認よろしくお願い致します！🙇‍♂️

2023-10-02 14:36 UTC, Naoto0213 requested changes
少しだけ！

2023-10-02 14:36 UTC, Naoto0213 commented on components/ErrorComponent.tsx
> +const ErrorComponent = ({ message }: Props) => {
ErrorComponentという命名は微妙かなと思います！
コンポーネントという命名を付けるメリットがないと思いました。

ErrorMessageなどで良いのではないでしょうか！

2023-10-02 14:36 UTC, Naoto0213 commented on pages/staff/[id].tsx
> +    return <ErrorComponent message="スタッフデータが見つかりませんでした" />;
良いですね☺️

2023-10-02 14:36 UTC, Naoto0213 commented on pages/staff/new-create.tsx
>          if (result.data && result.data.insert_staff_one) {
JSXでスネークケースを使用するのは避けたいので、キャメルケースに直しておきましょう。
const newStaffId = data.insert_staff_one.id 的な

2023-10-02 15:40 UTC, masaaki-todoroki commented
修正してみました！
お手隙のときにご確認、よろしくお願い致します🙇‍♂️

2023-10-03 05:10 UTC, merged